### ISSUE TITLE
Unable to build Development branch

### ISSUE THREAD

**Issue by benmeyer50** [CERT-BDF/TheHive#136]
# Unable to build development branch

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7
| OS version (client)       | Win 7
| TheHive version / git hash   | commit f61ad6ad2c20766b79ba0b200873915be1a8a8e6
| Package Type              | From Source

### Problem Description
Unable to build development branch

### Steps to Reproduce
1. git clone https://github.com/CERT-BDF/TheHive.git
2. git checkout develop
3. bin/activator clean stage

### Possible Solutions
Missing correct version of elastic4play in bintray repository

### Complementary information
```
sbt.ResolveException: unresolved dependency: org.cert-bdf#elastic4play_2.11;1.1.3-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (thehiveBackend/*:update) sbt.ResolveException: unresolved dependency: org.cert-bdf#elastic4play_2.11;1.1.3-SNAPSHOT: not found
```

**Comment by nadouani** [comment]
Hi @benmeyer50 

The develop branch of TheHive requires in fact a elastic4play version 1.1.3-SNAPSHOT (a development version too).

You can get the sources of elastic4play library, and build it's develop branch. (We don't publish SNAPSHOTs on bintray)

Elastic4play is a scala application, you can build it using `sbt` using the following command:

```
sbt publishLocal
```

So to summaries

```
git clone https://github.com/CERT-BDF/elastic4play.git
cd elastic4play
sbt publishLocal
```

Once it's build, and published locally, you can relaunch TheHive from sources.

I hope it helps.

**Comment by benmeyer50** [comment]
Hi @nadouani 

Awesome! Thank you!
