### ISSUE TITLE
Upgrade to 2.11.1-1 leads to restart issues with MISP

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/TheHive#217]
### Request Type

Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| TheHive version / git hash   | 2.11.1
| Package Type              | Debian package

### Problem Description
After upgrading from the hive 2.10.2 (binary) to 2.11.1 (Debian) thehive dies during connection attemp to MISP:
```
May 19 09:40:35 debian-8-user systemd[1]: Started TheHive.
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] o.r.Reflections - Reflections took 5588 ms to scan 124 urls, producing 7334 keys and 76175 values
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.AuditModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.AlertModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.CaseTemplateModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.CaseModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.ArtifactModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.UserModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class connectors.cortex.models.ReportTemplateModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.TaskModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class org.elastic4play.services.DBListModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class connectors.cortex.models.JobModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class org.elastic4play.services.AttachmentModel
May 19 09:40:43 debian-8-user thehive[13718]: [#033[37minfo#033[0m] module - Loading model class models.LogModel
May 19 09:40:47 debian-8-user thehive[13718]: [#033[37minfo#033[0m] o.r.Reflections - Reflections took 4277 ms to scan 124 urls, producing 7334 keys and 76175 values
May 19 09:40:51 debian-8-user thehive[13718]: [#033[37minfo#033[0m] o.r.Reflections - Reflections took 4199 ms to scan 124 urls, producing 7334 keys and 76175 values
May 19 09:40:53 debian-8-user thehive[13718]: [#033[37minfo#033[0m] a.e.s.Slf4jLogger - Slf4jLogger started
May 19 09:40:53 debian-8-user thehive[13718]: [#033[37minfo#033[0m] o.e.plugins - [Dracula] modules [], plugins [], sites []
May 19 09:40:55 debian-8-user thehive[13718]: [#033[37minfo#033[0m] c.m.MispConnection - Add MISP connection 2 (https://misp.internal.dom)
May 19 09:40:55 debian-8-user thehive[13718]: proxy configuration: None
May 19 09:40:55 debian-8-user thehive[13718]: [#033[37minfo#033[0m] c.misp.MispSrv - Update of MISP events is starting ...
May 19 09:40:55 debian-8-user thehive[13718]: [#033[37minfo#033[0m] c.misp.MispSrv - subscribe actor
May 19 09:40:57 debian-8-user thehive[13718]: [#033[37minfo#033[0m] play.api.Play - Application started (Prod)
May 19 09:40:57 debian-8-user thehive[13718]: [#033[37minfo#033[0m] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
May 19 09:40:57 debian-8-user thehive[13718]: [#033[37minfo#033[0m] c.misp.MispSrv - Misp synchronization failed
May 19 09:40:57 debian-8-user thehive[13718]: java.net.ConnectException: General SSLEngine problem
May 19 09:40:57 debian-8-user thehive[13718]: at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:162)
May 19 09:40:57 debian-8-user thehive[13718]: at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:133)
May 19 09:40:57 debian-8-user thehive[13718]: at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.ssl.SslHandler.notifyHandshakeFailure(SslHandler.java:1238)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1233)
May 19 09:40:57 debian-8-user thehive[13718]: Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
May 19 09:40:57 debian-8-user thehive[13718]: at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
May 19 09:40:57 debian-8-user thehive[13718]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
May 19 09:40:57 debian-8-user thehive[13718]: Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker$1.run(Handshaker.java:966)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker$1.run(Handshaker.java:963)
May 19 09:40:57 debian-8-user thehive[13718]: at java.security.AccessController.doPrivileged(Native Method)
May 19 09:40:57 debian-8-user thehive[13718]: Caused by: sun.security.validator.ValidatorException: KeyUsage does not allow digital signatures
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:270)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:141)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.validator.Validator.validate(Validator.java:264)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1501)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
May 19 09:40:57 debian-8-user thehive[13718]: at sun.security.ssl.Handshaker$1.run(Handshaker.java:966)
```

### Complementary information
1. I would assume that if a connection issue to MISP exists, thehive still works
2. I do not understand the error message.
3. It seems to have issues with the certificate. I wonder, as I did not do any changes to certificates. Do you have any Debugging hints?

**Comment by To-om** [comment]
This is an SSL error: ValidatorException: KeyUsage does not allow digital signatures.

The error actually comes from verifying the MISP server's certificate. That certificate has a key usage section that doesn't include a digitalSignature bit.

Some cipher suites require the digital signature bit, specifically Diffie-Hellman key exchange (DHE_RSA and ECDHE_RSA). You may be able to avoid this error by avoiding those cipher types. Otherwise the server certificate needs to support it.
(text from http://stackoverflow.com/questions/15355031/keyusage-does-not-allow-digital-signatures)

Try to create a new certificate for your MISP server, if possible.
Otherwise, you can try to change cipher suite (see [documentation](https://github.com/CERT-BDF/TheHiveDocs/blob/master/admin/configuration.md#ciphers))

**Comment by crackytsi** [comment]
Thank you. I will test this later.
I really wonder why this issue was raised after upgrade...

**Comment by crackytsi** [comment]
sorry I'm still analyzing. I recreated a new CA and new server certificate, but I'm still faced with issues:

```

2017-05-22 11:51:39,948 [INFO] from connectors.misp.MispSrv in application-akka.actor.default-dispatcher-3 - Misp synchronization failed
java.net.ConnectException: General SSLEngine problem
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:162)
        at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:133)
        at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
        at io.netty.handler.ssl.SslHandler.notifyHandshakeFailure(SslHandler.java:1238)
        at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1233)
        at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1208)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1063)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:966)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:963)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416)
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1123)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1008)
        ... 18 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)

```

Is there any option to temporary disable cert checking?

**Comment by crackytsi** [comment]
Hi,
I got it working today :)
From my Point of view this topic can be closed. I'm not sure if this is in any Kind a reminder for doing some Output optimizations, otherwise just Close it :)

I just can add the info if anyone else falls into this trap: There was a Change from the last Version to this Version related to certificate Handlings. The Extended attributes are now handled more restrictive than before. But this is according to the RFCs ;)

**Comment by nut1lns** [comment]
how do you solve this problem ?
